Fifth milestone
Leon-Mbegera/calculator pull request #4
Opened 2021-10-22 17:04 UTC by Leon-Mbegera

In milestone 5
-  I have tied the calculating logic with my components
- Added interactions to the buttons,
- Now its a working calculator

2021-10-22 17:39 UTC, addod19 requested changes
### Hi @Leon-Mbegera, 

Good job so far! Git-flow followed :+1: PR and README professional :100: App functional component converted into a class component :1st_place_medal: Buton Panel implemented as expected :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Using ES6 arrow syntax to keep up with the consistency with using the ES6 features

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-22 17:39 UTC, addod19 commented on README.md
> +[click me](https://leon-calc.herokuapp.com)
### Optional
- [x] It would be better if our live link or deployed version represents our actual app in development

2021-10-22 17:39 UTC, addod19 commented on src/components/ButtonPanel.js
> +
- [x] It would be better if we implement the `handleClick` function in the buttonPanel component, this way we make our buttonPanel component reusable
```
handleClick = (buttonName) => {
  this.props.clickHandler(buttonName);
};

```

2021-10-22 17:39 UTC, addod19 commented on src/components/ButtonPanel.js
> +    <div>
- [x] It would be better if we implement the functionality where users can work with decimals. For example;
```
2.3 + 4.6
```
I am unable to use the decimal point in the operation. Kindly fix that

2021-10-22 17:39 UTC, addod19 commented on src/components/ButtonPanel.js
> +      <div>
### Optional
- [x] It would be better if we implement error handling for the division by zero logic. For example; 5 / 0 should output "cannot divide by zero" but currently I gives us 0 and this is mathematically wrong

2021-10-22 17:39 UTC, addod19 commented on src/components/ButtonPanel.js
> +    </div>
### Optional
- [ ] It would be better to [map these](https://coursework.vschool.io/mapping-components-in-react/)

2021-10-23 16:43 UTC, taiwo2 approved these changes
Hi @Leon-Mbegera , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-23 16:43 UTC, taiwo2 commented on src/components/Button.js
> +function Button({ show, onClick }) {
# Optional

- [ ]  Using ES6 arrow syntax to keep up with the consistency with using the ES6 features

2021-10-23 16:43 UTC, taiwo2 commented on src/components/ButtonPanel.js
> +    </div>
# Optional
 It would be better to map these as stated y the previous code Reviewer

2021-10-25 08:48 UTC, merged